# Generated by Django 4.2.3 on 2023-08-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0004_advertisement_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='negotiable',
            new_name='auction',
        ),
    ]
